package models

type MkMeta struct {
	MaintainerName           string      `json:"maintainerName"`
	MaintainerEmail          string      `json:"maintainerEmail"`
	Version                  string      `json:"version"`
	Name                     string      `json:"name"`
	URI                      string      `json:"uri"`
	Description              string      `json:"description"`
	Langs                    []string    `json:"langs"`
	TosURL                   interface{} `json:"tosUrl"`
	RepositoryURL            string      `json:"repositoryUrl"`
	FeedbackURL              string      `json:"feedbackUrl"`
	DisableRegistration      bool        `json:"disableRegistration"`
	EmailRequiredForSignup   bool        `json:"emailRequiredForSignup"`
	EnableHCaptcha           bool        `json:"enableHcaptcha"`
	HCaptchaSiteKey          string      `json:"hcaptchaSiteKey"`
	EnableRecaptcha          bool        `json:"enableRecaptcha"`
	RecaptchaSiteKey         interface{} `json:"recaptchaSiteKey"`
	EnableTurnstile          bool        `json:"enableTurnstile"`
	TurnstileSiteKey         interface{} `json:"turnstileSiteKey"`
	SwPublicKey              string      `json:"swPublickey"`
	ThemeColor               string      `json:"themeColor"`
	MascotImageURL           string      `json:"mascotImageUrl"`
	BannerURL                string      `json:"bannerUrl"`
	ErrorImageURL            string      `json:"errorImageUrl"`
	IconURL                  string      `json:"iconUrl"`
	BackgroundImageURL       string      `json:"backgroundImageUrl"`
	LogoImageURL             interface{} `json:"logoImageUrl"`
	MaxNoteTextLength        int         `json:"maxNoteTextLength"`
	EnableEmail              bool        `json:"enableEmail"`
	EnableTwitterIntegration bool        `json:"enableTwitterIntegration"`
	EnableGithubIntegration  bool        `json:"enableGithubIntegration"`
	EnableDiscordIntegration bool        `json:"enableDiscordIntegration"`
	EnableServiceWorker      bool        `json:"enableServiceWorker"`
	TranslatorAvailable      bool        `json:"translatorAvailable"`
	Policies                 struct {
		GtlAvailable           bool `json:"gtlAvailable"`
		LtlAvailable           bool `json:"ltlAvailable"`
		CanPublicNote          bool `json:"canPublicNote"`
		CanInvite              bool `json:"canInvite"`
		CanManageCustomEmojis  bool `json:"canManageCustomEmojis"`
		DriveCapacityMb        int  `json:"driveCapacityMb"`
		PinLimit               int  `json:"pinLimit"`
		AntennaLimit           int  `json:"antennaLimit"`
		WordMuteLimit          int  `json:"wordMuteLimit"`
		WebhookLimit           int  `json:"webhookLimit"`
		ClipLimit              int  `json:"clipLimit"`
		NoteEachClipsLimit     int  `json:"noteEachClipsLimit"`
		UserListLimit          int  `json:"userListLimit"`
		UserEachUserListsLimit int  `json:"userEachUserListsLimit"`
		RateLimitFactor        int  `json:"rateLimitFactor"`
	} `json:"policies"`
	PinnedPages      []string    `json:"pinnedPages"`
	PinnedClipID     interface{} `json:"pinnedClipId"`
	CacheRemoteFiles bool        `json:"cacheRemoteFiles"`
	RequireSetup     bool        `json:"requireSetup"`
	ProxyAccountName interface{} `json:"proxyAccountName"`
	Features         struct {
		Registration           bool `json:"registration"`
		EmailRequiredForSignup bool `json:"emailRequiredForSignup"`
		Elasticsearch          bool `json:"elasticsearch"`
		HCaptcha               bool `json:"hcaptcha"`
		Recaptcha              bool `json:"recaptcha"`
		Turnstile              bool `json:"turnstile"`
		ObjectStorage          bool `json:"objectStorage"`
		Twitter                bool `json:"twitter"`
		Github                 bool `json:"github"`
		Discord                bool `json:"discord"`
		ServiceWorker          bool `json:"serviceWorker"`
		MiAuth                 bool `json:"miauth"`
	} `json:"features"`
}
